# Generated by Django 5.0.7 on 2024-07-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=500)),
                ('category_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='New_Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_des', models.CharField(max_length=500)),
                ('product_image', models.ImageField(upload_to='images/')),
                ('old_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('seller', models.CharField(max_length=100)),
                ('trend', models.BooleanField(default=False)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_des', models.CharField(max_length=500)),
                ('product_image', models.ImageField(upload_to='images/')),
                ('old_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('seller', models.CharField(max_length=100)),
                ('trend', models.BooleanField(default=False)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
