# Generated by Django 4.2.11 on 2024-07-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_faq_logins_orders_category_cate_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
